version: '3.5'

networks:
  app-buscapets:
    driver: bridge

volumes:
  mysql_buscapets:
    driver: local

services:
  mysql:
    container_name: mysql_container
    image: mysql:5.7
    networks:
      - app-buscapets
    environment:
      MYSQL_DATABASE: buscapets
      MYSQL_USER: buscapets
      MYSQL_PASSWORD: sqlP4SS
      MYSQL_ROOT_PASSWORD: RO0TsqlP4SS
    ports:
      - '3308:3306'
    volumes:
      - mysql_buscapets:/usr/buscapets/datadir
    restart: always

  api:
    build: .
    restart: always
    container_name: api_buscapets
    networks:
      - app-buscapets
    depends_on:
      - mysql
    ports:
      - '3002:3002'
    volumes:
      - ./src:/usr/buscapets/src
      - ./.env:/usr/buscapets/.env
    command: yarn start:dev
