version: '3.5'

services:
  api:
    build: .
    restart: always
    container_name: api-buscapets
    depends_on:
      - mysql
    ports:
      - '3002:3002'
    volumes:
      - ./src:/usr/buscapets/src
      - ./.env:/usr/buscapets/.env
    command: sh -c 'yarn build && yarn start:prod && yarn cache clean'

  mysql:
    container_name: mysql-container
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: buscapets
      MYSQL_USER: buscapets
      MYSQL_PASSWORD: sqlP4SS
      MYSQL_ROOT_PASSWORD: RO0TsqlP4SS
    ports:
      - '3307:3306'
    volumes:
      - .:/usr/buscapets/datadir
    restart: always